### ISSUE TITLE
UnknownError: 2 root error(s) found

### ISSUE THREAD

**Issue by asifehmad** [nikhilroxtomar/Polyp-Segmentation-using-UNET-in-TensorFlow-2.0#3]
Hello! Hope your doing great. I just wanted to reproduce the results. Every thing was going smoothly then this error prompted at the end in `predict.py` file. I am trying this on  _Google Colab_ Details of the error are given below, kindly check.
![error 1](https://user-images.githubusercontent.com/54246513/101283893-2dd42c80-37ff-11eb-9773-f8c66411056c.PNG)
![error 2](https://user-images.githubusercontent.com/54246513/101283904-2f9df000-37ff-11eb-8940-4f26edf79e8d.PNG)

The code line to which the error points is:
![error 3](https://user-images.githubusercontent.com/54246513/101283964-7855a900-37ff-11eb-92a8-ecd89624812c.PNG)
 The folders, `files` and `results` are inside another folder named as `Filess` and I have changed the directory to the that too.

Any help would be greatly appreciated. Thanks!

**Comment by nikhilroxtomar** [comment]
I think the path of the image is incorrect, that is why the function
cv2.imread is returning NULL value.

**Comment by bhsnada** [comment]
hello how do you fixed this error
![image](https://user-images.githubusercontent.com/33868302/114525021-075b4d80-9c46-11eb-87ab-ec3075b94d2e.png)

![image](https://user-images.githubusercontent.com/33868302/114525154-2823a300-9c46-11eb-9f1a-e6646c562e19.png)

**Comment by AsifAhmadKhan** [comment]
mail me at ***@***.*** ***@***.***>*

**Comment by bhsnada** [comment]
I can't read your email address

**Comment by bhsnada** [comment]
hello

thank you for your feedback

Any help would be greatly appreciated.

Le mar. 13 avr. 2021 à 11:03, Asif Ahmad Khan ***@***.***> a
écrit :

> mail me at ***@***.*** ***@***.***>*
>
>
>
>
> On Tue, Apr 13, 2021 at 1:51 PM Bel Hadj Slimen Nada <
