### ISSUE TITLE
Images are saved as grayscale

### ISSUE THREAD

**Issue by asifehmad** [nikhilroxtomar/Polyp-Segmentation-using-UNET-in-TensorFlow-2.0#4]
Hi Nikhil,
                thank you for the project. I reproduced the results, everything went well till the end. But I have got the original as a grayscale image at the end in the results folders. I don't know why. Your help will be appreciated in this regard.
Thanks,
Asif Ahmad

**Comment by nikhilroxtomar** [comment]
I think the CVC-ClinicDB dataset has been updated with grayscale images. Working with grayscale image should not have any issue. You can use another colonoscopy dataset like Kvasir-SEG https://datasets.simula.no/kvasir-seg/

**Comment by asifehmad** [comment]
> I think the CVC-ClinicDB dataset has been updated with grayscale images. Working with grayscale image should not have any issue. You can use another colonoscopy dataset like Kvasir-SEG https://datasets.simula.no/kvasir-seg/

Thank you, NikhI. I just cross checked the images, they are colorful (RGB). I am trying the code on Google Colab.
